export const CALLBACK_TYPE_BENCH = 'CALLBACK_TYPE_BENCH';
export const CALLBACK_TYPE_CONFIRM = 'CALLBACK_TYPE_CONFIRM';
export const CALLBACK_TYPE_LINEUP = 'CALLBACK_TYPE_LINEUP';
export const CALLBACK_TYPE_LOTTERY = 'CALLBACK_TYPE_LOTTERY';
export const CALLBACK_TYPE_UNCONFIRM = 'CALLBACK_TYPE_UNCONFIRM';
